"""Add photo field to pets table

Revision ID: 54f43e0efe7b
Revises: b2f3ce254fec
Create Date: 2025-12-03 22:28:52.538633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f43e0efe7b'
down_revision: Union[str, None] = 'b2f3ce254fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('photo', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'photo')
    # ### end Alembic commands ###

