"""Initial migration - create all tables

Revision ID: b2f3ce254fec
Revises: 
Create Date: 2025-12-03 21:40:08.225644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f3ce254fec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ectoparasites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_praga', sa.String(length=255), nullable=False),
    sa.Column('tipo_praga', sa.String(length=100), nullable=False),
    sa.Column('especies_alvo', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('transmissor_de_doencas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sintomas_no_animal', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('medicamentos_de_combate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observacoes_adicionais', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ectoparasites_nome', 'ectoparasites', ['nome_praga'], unique=False)
    op.create_index('idx_ectoparasites_tipo', 'ectoparasites', ['tipo_praga'], unique=False)
    op.create_index(op.f('ix_ectoparasites_nome_praga'), 'ectoparasites', ['nome_praga'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('pedigree_number', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('pet_type', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male', 'female')", name='chk_gender'),
    sa.CheckConstraint("pet_type IN ('cat', 'dog')", name='chk_pet_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index('idx_pets_deleted', 'pets', ['deleted_at'], unique=False)
    op.create_index('idx_pets_nickname', 'pets', ['nickname'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_index(op.f('ix_pets_pet_type'), 'pets', ['pet_type'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('is_vet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profiles_deleted', 'profiles', ['deleted_at'], unique=False)
    op.create_index('idx_profiles_email', 'profiles', ['email'], unique=False)
    op.create_index('idx_profiles_is_vet', 'profiles', ['is_vet'], unique=False)
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=False)
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_vacina', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('especie_alvo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vacina', sa.String(length=100), nullable=False),
    sa.Column('protege_contra', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('efeitos_colaterais', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cronograma_vacinal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vaccines_especie', 'vaccines', ['especie_alvo'], unique=False)
    op.create_index('idx_vaccines_nome', 'vaccines', ['nome_vacina'], unique=False)
    op.create_index('idx_vaccines_tipo', 'vaccines', ['tipo_vacina'], unique=False)
    op.create_index(op.f('ix_vaccines_especie_alvo'), 'vaccines', ['especie_alvo'], unique=False)
    op.create_index(op.f('ix_vaccines_nome_vacina'), 'vaccines', ['nome_vacina'], unique=False)
    op.create_table('vermifugos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_praga', sa.String(length=255), nullable=False),
    sa.Column('tipo_praga', sa.String(length=100), nullable=False),
    sa.Column('especies_alvo', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sintomas_no_animal', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('medicamentos_de_combate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observacoes_adicionais', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vermifugos_nome', 'vermifugos', ['nome_praga'], unique=False)
    op.create_index('idx_vermifugos_tipo', 'vermifugos', ['tipo_praga'], unique=False)
    op.create_index(op.f('ix_vermifugos_nome_praga'), 'vermifugos', ['nome_praga'], unique=False)
    op.create_table('pet_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'profile_id', name='uq_pet_owner')
    )
    op.create_index('idx_pet_owners_pet', 'pet_owners', ['pet_id'], unique=False)
    op.create_index('idx_pet_owners_profile', 'pet_owners', ['profile_id'], unique=False)
    op.create_table('treatments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('applier_type', sa.String(length=50), nullable=False),
    sa.Column('applier_name', sa.String(length=255), nullable=True),
    sa.Column('applier_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("applier_type IN ('Veterinarian', 'Tutor')", name='chk_applier_type'),
    sa.CheckConstraint("category IN ('Vacinas', 'Ectoparasitas', 'Vermífugo', 'Tratamentos')", name='chk_category'),
    sa.ForeignKeyConstraint(['applier_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treatments_category', 'treatments', ['category'], unique=False)
    op.create_index('idx_treatments_date', 'treatments', ['date'], unique=False)
    op.create_index('idx_treatments_pending', 'treatments', ['pet_id', 'done', 'date'], unique=False)
    op.create_index('idx_treatments_pet', 'treatments', ['pet_id'], unique=False)
    op.create_index(op.f('ix_treatments_date'), 'treatments', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatments_date'), table_name='treatments')
    op.drop_index('idx_treatments_pet', table_name='treatments')
    op.drop_index('idx_treatments_pending', table_name='treatments')
    op.drop_index('idx_treatments_date', table_name='treatments')
    op.drop_index('idx_treatments_category', table_name='treatments')
    op.drop_table('treatments')
    op.drop_index('idx_pet_owners_profile', table_name='pet_owners')
    op.drop_index('idx_pet_owners_pet', table_name='pet_owners')
    op.drop_table('pet_owners')
    op.drop_index(op.f('ix_vermifugos_nome_praga'), table_name='vermifugos')
    op.drop_index('idx_vermifugos_tipo', table_name='vermifugos')
    op.drop_index('idx_vermifugos_nome', table_name='vermifugos')
    op.drop_table('vermifugos')
    op.drop_index(op.f('ix_vaccines_nome_vacina'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_especie_alvo'), table_name='vaccines')
    op.drop_index('idx_vaccines_tipo', table_name='vaccines')
    op.drop_index('idx_vaccines_nome', table_name='vaccines')
    op.drop_index('idx_vaccines_especie', table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_index('idx_profiles_is_vet', table_name='profiles')
    op.drop_index('idx_profiles_email', table_name='profiles')
    op.drop_index('idx_profiles_deleted', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_pets_pet_type'), table_name='pets')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index('idx_pets_nickname', table_name='pets')
    op.drop_index('idx_pets_deleted', table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_ectoparasites_nome_praga'), table_name='ectoparasites')
    op.drop_index('idx_ectoparasites_tipo', table_name='ectoparasites')
    op.drop_index('idx_ectoparasites_nome', table_name='ectoparasites')
    op.drop_table('ectoparasites')
    # ### end Alembic commands ###

